# Generated by Django 4.2.2 on 2023-06-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage_view',
            name='url',
            field=models.URLField(),
        ),
    ]
